### ISSUE TITLE
Command arguments

### ISSUE THREAD

**Issue by haloflooder** [ClubObsidian/DynamicGui#103]
Instead of completely ignoring arguments from commands. Could utilize them for gui's.

Spec is still completely open for suggestions. This is just an initial idea for command arguments.

```yaml
title: "Example"
rows: 6
alias:
- "command"

# Everything desc below are just examples
# Lets say player does command `/command Notch 2019 "Hello world" foo bar`
# If "must have args" is true, shows "/command <player name> <year> <title> <desc>"
command-args:
  must-have-args: true
  args:
    '1':
      type: player # Can be player for online or offline player
      online: true
      desc: "<player name>"
    '2':
      type: number
      desc: "<year>"
    '3':
      type: text
      support-quotes: true
      desc: "<title>"
    '4':
      type: text
      support-quotes: true
      desc: "<desc>"

"0":
  icon: SKULL_ITEM
  nbt: "{skullwhatever:%arg-1-uuid%}"
  name: "%arg-2%" # Should be Hello world
  lore:
  - "Player: %arg-1%" # Should be Notch
  - "Player: %arg-1-uuid%" # should be Notch's uuid (if online)
  - "Year: %arg-3%"
  - "Description: %arg 4%" # Should be Foo bar
```

**Comment by haloflooder** [comment]
A simpler spec could be something like this

`/command haloflooder foo "Some Title" "Some more text"`

```yml
title: "Example"
rows: 6
alias:
- "command"

"0":
  icon: PLAYER_HEAD
  name: "%arg-3%" # Should be "Some Title"
  lore:
  - "Player: %arg-1%" # Should be haloflooder
  - "Description: %arg-4%" # Should be "Some more text"
  functions:
    onLoad:
      type: load
      functions:
        - "playerisonline: %arg-1%" # Lets pretend this function actually exists
        - "setnbt: {skullwhatever:%player_skin_%arg-1%%}"
    checkFoo:
      type: load
      functions:
        - "condition: STREQUAL('%arg-2%', 'foo')"
        - "pmsg: You chose FOO"
    checkBar:
      type: load
      functions:
        - "condition: STREQUAL('%arg-2%', 'bar')"
        - "pmsg: You chose BAR"
```
