### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by virustotalop** [ClubObsidian/DynamicGui#137]
Allow guis to paginate, this should be done at load time. The question is though how should guis be loaded in and referenced?

```yaml
rows: 1
0:
  icon: "DIRT"
1:
  icon: "DIRT"
2:
  icon: "DIRT"
3:
  icon: "DIRT"
4:
  icon: "DIRT"
5:
  icon: "DIRT"
6:
  icon: "DIRT"
7:
  icon: "DIRT"
8:
  icon: "DIRT"
9:
  icon: "DIRT"
```

If this gui is named test-gui, should it be parsed into "test-gui1" and "test-gui-2" or should it be handled differenlt?
