### ISSUE TITLE
[Request] getPlayerInput function

### ISSUE THREAD

**Issue by lrmtheboss** [ClubObsidian/DynamicGui#213]
Add a function to have the player give input by typing it into the chat box when requested and then set a slot metaData value when input is gotten, for use in later functions

GUI function example

```yml
functions:
  - "getPlayerInput: (metaData to store input into), (description of input required)"
  or
    # this case the function would handle input validation which would be best as
    #    otherwise we would need another function to check/validate data
  - "getPlayerInput: (metaData to store input into), (input validation), (description of input required)"
```
For input validation could do int(<10), int(>5), int(5<10), String(maybe regex check) or use condition function for validation

The 'getPlayerInput' function when called should send a message to the player to let the player know that they need to give input and a description of what type of input is required (description of input required). Then it should close the GUI and wait for input for a set amount of time. If no input is gotten within the set amount of time it should send an error message to the player that no input was given (maybe reopen the previous `GUI)` and cancel the execution of the remaining functions in that slot
