### ISSUE TITLE
Functions fall through when a function fails

### ISSUE THREAD

**Issue by virustotalop** [ClubObsidian/DynamicGui#236]
Functions fall through to the next function even if the function fails on the 5.x branch. Example

With an account with `*` before should run and then the permission test should fail. Which should then broadcast `You had the permission`. Currently this broadcasts `Not permission` as well.
```yaml
'44':
  icon: "DIAMOND_SWORD"
  name: "Test dirt 44"
  enchants:
  - "DAMAGE_ALL,1"
  item-flags:
  - "HIDE_ATTRIBUTES"
  functions:
    shop:
      type: "click"
      functions:
      - "broadcast: before"
      - "!permission: test"
      - "broadcast: Not permission"
      fail-permission:
        type: "fail"
        fail-on: "!permission"
        functions:
        - "broadcast: You had the permission"
 ```
