### ISSUE TITLE
Add support to refresh/update the gui slot/inventory

### ISSUE THREAD

**Issue by haloflooder** [ClubObsidian/DynamicGui#47]
Being able to refresh/update a gui slot/inventory would be nice for live updates for replacers or to add a removed item back to the gui if they have permission for it.

e.g.
```
'20':
  icon: "BEDROCK"
  name: "&bTest"
  lore:
  - "&aYou have permission for test.test!"
  updateEvery: 20 # update every 20 ticks
  load-functions:
  - "permission: test.test"
  permission-loadfailfunctions:
  - "setlore: &cYou don't have permission for test.test"
```
or
```
'20':
  icon: "BEDROCK"
  name: "&bTest"
  lore:
  - "&aYou have permission for test.test!"
  load-functions:
  - "refreshSlotIn: 20"
  - "permission: test.test"
  permission-loadfailfunctions:
  - "setlore: &cYou don't have permission for test.test"
```
