### ISSUE TITLE
New function system for 4.0.0

### ISSUE THREAD

**Issue by virustotalop** [ClubObsidian/DynamicGui#59]
New function system should work like this
Also allow for treeing of functions so fail functions can have fail functions and can have functions etc. Functions should also have branches out to be able to run other functions whenever those functions are ran.

```
title: "test gui title"
rows: 1
mode: "set"
close: true
npcs:
  citizens:
  - 5
  - 77

functions:
  function: #Fails on function fail, considered a global function, if you want bound to one slot put under own section
    type: "fail"
    fail-on: "function" #Can also be a list, if 'fail-on' is not specified runs for all.
    functions:
    - "function"

'0':
  name: "Some name"
  replacers:
     '%test%': "This is some text"
  functions:
    load:
      type: 
      - "load"
      functions:
      - "function: with data"
      - "function-to-normalize"
      depth-1-load:
        type:
        - "load"
        functions:
        - "function: with other data"
    leftclick:
      type:
      - "left"
      functions:
      - "function"
      depth-1-left:
        type:
        - "left"
        functions:
        - "function"
        depth-2-left:
          type: 
          - "left"
          functions:
          - "function: some other data"
      depth-1-other-left:
        type:
        - "left"
        functions:
        - "function"
    allclick:
      type:
      - "left"
      - "right"
      - "middle" 
      functions:
      - "function"
      - "function: with:a colon"
      - "functions:  test trimming   "
'1': #First SlotToken test
  name: "test"
  icon: "DIRT"
  nbt: "{SomeKey:\"some value\"}"
  close: true
  data: 1
  functions:
    left:
      type:
      - "left"
      functions:
      - "function"   
```
